structure(list(url = "https://api.stlouisfed.org/fred/series/observations?series_id=bad_series_id&api_key=d3ef3490ef7270cf903d07141e9e7db7&file_type=json", 
    status_code = 400L, headers = structure(list(`content-type` = "application/json; charset=UTF-8", 
        `content-length` = "146", server = "Apache", date = "Wed, 20 May 2020 05:24:58 GMT", 
        connection = "keep-alive"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json; charset=UTF-8", 
            `content-length` = "146", server = "Apache", date = "Wed, 20 May 2020 05:24:58 GMT", 
            connection = "keep-alive"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"error_code\":400,\"error_message\":\"Bad Request.  Invalid value for variable series_id.  Series IDs should be 25 or less alphanumeric characters.\"}"), 
    date = structure(1589952298, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4e-05, 
    connect = 4.2e-05, pretransfer = 0.000112, starttransfer = 0.219658, 
    total = 0.219705)), class = "response")
