structure(list(url = "https://api.stlouisfed.org/fred/series?api_key=d3ef3490ef7270cf903d07141e9e7db7&file_type=json", 
    status_code = 400L, headers = structure(list(`content-type` = "application/json; charset=UTF-8", 
        `content-length` = "87", server = "Apache", date = "Wed, 20 May 2020 05:24:58 GMT", 
        connection = "keep-alive"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json; charset=UTF-8", 
            `content-length` = "87", server = "Apache", date = "Wed, 20 May 2020 05:24:58 GMT", 
            connection = "keep-alive"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"error_code\":400,\"error_message\":\"Bad Request.  Variable series_id has not been set.\"}"), 
    date = structure(1589952298, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.8e-05, 
    connect = 4.1e-05, pretransfer = 9.8e-05, starttransfer = 0.16369, 
    total = 0.163723)), class = "response")
